spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    #    url: jdbc:h2:mem:goomong
    url: jdbc:h2:tcp://localhost/~/test
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  session:
    jdbc:
      initialize-schema: always
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail: # smtp
    host: smtp.google.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      smtp:
        auth: true
        timeout: 5000
        starttls:
          enable: true

File:
  upload:
    path: "C:\\upload"

server:
  error:
    include-message: always
    include-binding-errors: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
