spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:mem:goomong
    #url: jdbc:h2:tcp://localhost/~/test
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  session:
    jdbc:
      initialize-schema: always

File:
  upload:
    path: "C:\\upload"

server:
  error:
    include-message: always
    include-binding-errors: always
