spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:mem:goomong
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  session:
    jdbc:
      initialize-schema: always


File:
  upload:
    path: "C:\\upload"