apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - nginx.yaml
  - mysqldb.yaml
  - backend.yaml
configMapGenerator:
  - name: nginx-config
    files:
      - default.conf=config/default.conf